### ISSUE TITLE
Unable to Confirm Action "Consult Faction Mission" to start infiltration

### ISSUE THREAD

**Issue by jagonchen** [WOTCStrategyOverhaul/CovertInfiltration#245] opened 2019-08-31 21:27 UTC
https://media.discordapp.net/attachments/578606792880291850/617468138996367390/unknown.png?width=1248&height=702

https://cdn.discordapp.com/attachments/578606792880291850/617470571130650625/save_AUTOSAVE-_Campaign_33_Mission_17

**Comment by Xymanek** [comment] 2019-09-02 06:36
So, I was digging into your save *for like 40 min* and I found the issue: `Sgt. Brian 'Hoss' Gordon` is deployed on `hunt assassin part 1`. The problem is that the fact that he is deployed is recorded in 2 places - and one of them wasn't updated for some reason.

What do you remember about deploying people on that action? any special interactions you did?

**Comment by Xymanek** [comment] 2019-09-02 07:48
In 76333a7 I added a redscreen to make this more easily noticeable in future

**Comment by jagonchen** [comment] 2019-09-02 16:14
No special interactions that I could remember I did.

**Comment by Xymanek** [comment] 2019-09-03 05:30
Did you do any missions since you launched that CA?

**Comment by jagonchen** [comment] 2019-09-03 14:23
Yes, and they worked fine except that in one mission I had a similiar problem. 

https://media.discordapp.net/attachments/578606792880291850/617483719686488120/unknown.png?width=1248&height=702

But In that case I could do the mission with 2 LT Rank soldiers.

**Comment by Xymanek** [comment] 2019-09-03 14:43
On that screenshot it's again the same bugged guy

**Comment by Xymanek** [comment] 2019-09-05 19:40
Closed due to inability to reproduce the core issue (unit not being marked as on CA but properly being assigned the staff slot)

**Closed by Xymanek** 2019-09-05 19:40 UTC
Labels: bug, gameplay, invalid, wontfix
