### ISSUE TITLE
No Dark Events At all

### ISSUE THREAD

**Issue by KaotiKnighT** [WOTCStrategyOverhaul/CovertInfiltration#580] opened 2020-09-30 09:37 UTC
Hi first time doing this ...
not a coder just a nub gamer
my game has stopped proccing dark events at the end of the month

[save_BUG Report no Dark Events.zip](https://github.com/WOTCStrategyOverhaul/CovertInfiltration/files/5304532/save_BUG.Report.no.Dark.Events.zip)

**Comment by KaotiKnighT** [comment] 2020-09-30 10:09
Screenshot

I am not using any mods that mess with Dark events to my knowledge anyway


![No Dark Events Bug Report](https://user-images.githubusercontent.com/72131669/94672545-beeadb00-0358-11eb-8b1b-80a4b9980415.png)

**Comment by KaotiKnighT** [comment] 2020-10-03 02:36
Update
So Dark Events are still occurring ...
I just am not getting any counter missions
they aren't being displayed on end of month screen
and when they become active I am not being notified

**Comment by Xymanek** [comment] 2020-10-29 06:41
Duplicate of #578 (decided to keep that one since it's older)

**Closed by Xymanek** 2020-10-29 06:41 UTC
Labels: bug, gameplay
